apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-processing-api
  description: API for processing payment transactions
  annotations:
    backstage.io/managed-by: guests
  tags:
    - payment
    - rest
    - secure
  links:
    - url: http://example.com/apis/payment-processing/
      title: API Documentation
    - url: http://example.com/apis/payment-processing/swagger
      title: Swagger UI
      icon: code
    - url: http://example.com/apis/payment-processing/status
      title: API Status
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: payment-platform
  definition:
    $text: ./payment-processing-api.oas.yaml
  providedBy: 
    - resource:payment-database
  consumedBy:
    - component:checkout-service

