apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rust_jenkins_test
  annotations:
    'backstage.io/kubernetes-namespace': backstage
spec:
  type: service
  lifecycle: experimental
  owner: guests