apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-integracion-bancos
  annotations:
    'backstage.io/kubernetes-namespace': backstage
spec:
  type: service
  lifecycle: production
  owner: guests