apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: payment-platform
  description: Payment platform handling product listings, inventory, and checkout processes
  tags:
    - e-commerce
    - platform
    - business-critical
  links:
    - url: http://example.com/systems/e-commerce/
      title: System Documentation
    - url: http://example.com/systems/e-commerce/architecture
      title: Architecture Diagram
    - url: http://example.com/systems/e-commerce/dashboard
      title: System Dashboard
      icon: dashboard
spec:
  type: system
  lifecycle: production
  owner: guests
  domain: sales
  components:
    - component:checkout-service
    - component:inventory-service
  providesApis:
    - payment-processing-api
  dependsOn:
    - resource:payment-processor

