apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: bank
  description: Main Bank domain
  links:
    - url: http://example.com/domain/audio/
      title: Domain Readme
    - url: http://example.com/domains/audio/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  # type: backstage-plugin
  lifecycle: experimental
  owner: guests
