apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: refund-service
  description: Service managing payment refunds
  annotations:
    backstage.io/managed-by: users
  links:
    - url: http://example.com/services/refund-service/
      title: Service Documentation
    - url: http://example.com/services/refund-service/dashboard
      title: Service Metrics Dashboard
      icon: dashboard
    - url: http://example.com/services/refund-service/api-docs
      title: API Documentation
      icon: code
spec:
  type: service
  lifecycle: production
  owner: guests
  system: payment-platform
  providesApis:
    - refund-service-api
  dependsOn:
    - resource:payment-database
  consumedBy:
    - component:checkout-service

