apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout-service
  description: Service handling customer checkout process
  annotations:
    backstage.io/managed-by: users
  tags:
    - payment-platform
    - checkout
    - customer-facing
  links:
    - url: http://example.com/services/checkout/
      title: Service Documentation
    - url: http://example.com/services/checkout/dashboard
      title: Service Metrics Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: guests
  system: payment-platform
  dependsOn:
    - resource:payment-database
    - component:inventory-service
    - component:refund-service
  consumesApis:
    - payment-processing-api

